<a href="https://colab.research.google.com/github/NurAhammedTonmoy/C/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

dataset=pd.read_csv('/content/processed_data2.csv')
dataset.head()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1708 entries, 0 to 1707
Data columns (total 38 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   phone_brand         1708 non-null   object
 1   phone_model         1708 non-null   object
 2   store               1708 non-null   object
 3   price_usd           1708 non-null   float64
 4   storage             1708 non-null   int64
 5   ram                 1708 non-null   int64
 6   launch_date         1708 non-null   object
 7   dimensions          1708 non-null   object
 8   weight              1708 non-null   float64
 9   display_type        1708 non-null   object
 10  display_size        1708 non-null   float64
 11  display_resolution  1708 non-null   object
 12  os                  1708 non-null   object
 13  nfc                 1708 non-null   int64
 14  usb                 1708 non-null   object
 15  battery             1708 non-null   int64
 16  features_sensors    1708 non-null   object
 17  colors              1708 non-null   object
 18  video               1708 non-null   object
 19  chipset             1708 non-null   object
 20  cpu                 1708 non-null   object
 21  gpu                 1708 non-null   object
 22  year                1708 non-null   object
 23  foldable            1708 non-null   int64
 24  ppi_density         1708 non-null   int64
 25  quantile_10         1708 non-null   float64
 26  quantile_50         1708 non-null   float64
 27  quantile_90         1708 non-null   float64
 28  price_range         1708 non-null   object
 29  os_type             1708 non-null   object
 30  os_version          1708 non-null   object
 31  battery_size        1708 non-null   object
 32  colors_available    1708 non-null   int64
 33  chip_company        1708 non-null   object
 34  cpu_core            1690 non-null   object
 35  gpu_company         1637 non-null   object
 36  fingerprint         1708 non-null   object
 37  video_resolution    1708 non-null   object
dtypes: float64(6), int64(7), object(25)
memory usage: 507.2+ KB

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4700 non-null   object
 1   Position      4700 non-null   object
 2   Age           4700 non-null   int64
 3   Team_from     4700 non-null   object
 4   League_from   4700 non-null   object
 5   Team_to       4700 non-null   object
 6   League_to     4700 non-null   object
 7   Season        4700 non-null   object
 8   Market_value  3440 non-null   float64
 9   Transfer_fee  4700 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 367.3+ KB

In [ ]:
#imputation -> model basse,mean,median,mode
dataset['Market_value']=dataset.Market_value.fillna(dataset.Market_value.mean())

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4700 non-null   object
 1   Position      4700 non-null   object
 2   Age           4700 non-null   int64
 3   Team_from     4700 non-null   object
 4   League_from   4700 non-null   object
 5   Team_to       4700 non-null   object
 6   League_to     4700 non-null   object
 7   Season        4700 non-null   object
 8   Market_value  4700 non-null   float64
 9   Transfer_fee  4700 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 367.3+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()
dataset['Name']=Le.fit_transform(dataset['Name'])

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4700 non-null   int64
 1   Position      4700 non-null   object
 2   Age           4700 non-null   int64
 3   Team_from     4700 non-null   object
 4   League_from   4700 non-null   object
 5   Team_to       4700 non-null   object
 6   League_to     4700 non-null   object
 7   Season        4700 non-null   object
 8   Market_value  4700 non-null   float64
 9   Transfer_fee  4700 non-null   int64
dtypes: float64(1), int64(3), object(6)
memory usage: 367.3+ KB

In [ ]:
dataset.head()

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee
0,1776,Right Winger,27,FC Barcelona,LaLiga,Real Madrid,LaLiga,2000-2001,8.622469e+06,60000000
1,1194,Centre-Forward,25,Parma,Serie A,Lazio,Serie A,2000-2001,8.622469e+06,56810000
2,1823,Left Winger,27,Arsenal,Premier League,FC Barcelona,LaLiga,2000-2001,8.622469e+06,40000000
3,1020,Centre-Forward,31,Fiorentina,Serie A,AS Roma,Serie A,2000-2001,8.622469e+06,36150000
4,2186,Centre-Forward,21,Real Madrid,LaLiga,Paris SG,Ligue 1,2000-2001,8.622469e+06,34500000

In [6]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Load the dataset
df = pd.read_csv('your_dataset.csv')  # replace with your actual CSV file path

# Make a copy
df_clean = df.copy()

# --- Step 1: Handle structured strings ---
# Parse display_resolution like "1080 x 2400"
df_clean[['res_width', 'res_height']] = df_clean['display_resolution'].str.extract(r'(\d+)\s*x\s*(\d+)').astype(float)

# Parse dimensions like "160.8 x 78.1 x 7.65 mm"
dims = df_clean['dimensions'].str.extract(r'(\d+\.?\d*)\s*x\s*(\d+\.?\d*)\s*x\s*(\d+\.?\d*)')
df_clean[['dim_length', 'dim_width', 'dim_thickness']] = dims.astype(float)

# Parse video_resolution like "4K@30fps" or "1080p@60fps"
df_clean['video_fps'] = df_clean['video'].str.extract(r'@(\d+)').astype(float)

# Convert launch_date to year
df_clean['launch_date'] = pd.to_datetime(df_clean['launch_date'], errors='coerce')
df_clean['launch_year'] = df_clean['launch_date'].dt.year.fillna(0).astype(int)

# --- Step 2: Drop unneeded or now-parsed columns ---
df_clean.drop(columns=[
    'display_resolution', 'dimensions', 'video', 'launch_date', 'year'
], inplace=True)

# --- Step 3: Clean battery_size ---
# Extract numeric part like "5000 mAh" → 5000
df_clean['battery_size'] = df_clean['battery_size'].str.extract(r'(\d+)').astype(float)

# --- Step 4: Handle object (categorical) columns ---
label_enc = LabelEncoder()

# Fill NA for categorical features
df_clean.fillna("Unknown", inplace=True)

for col in df_clean.select_dtypes(include='object').columns:
    df_clean[col] = label_enc.fit_transform(df_clean[col].astype(str))

# --- Step 5: Convert remaining columns to numeric ---
df_clean = df_clean.apply(pd.to_numeric, errors='ignore')

# --- Final check ---
print("Final shape:", df_clean.shape)
print(df_clean.head())

# Optionally, save it to a new CSV
df_clean.to_csv("cleaned_phone_data.csv", index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'your_dataset.csv'

In [8]:
import pandas as pd

dataset=pd.read_csv('/content/enhanced_box_office_data(2000-2024)u.csv')
dataset.head()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rank                  5000 non-null   int64
 1   Release Group         5000 non-null   object
 2   $Worldwide            5000 non-null   float64
 3   $Domestic             5000 non-null   float64
 4   Domestic %            5000 non-null   float64
 5   $Foreign              5000 non-null   float64
 6   Foreign %             5000 non-null   float64
 7   Year                  5000 non-null   int64
 8   Genres                4822 non-null   object
 9   Rating                4830 non-null   object
 10  Vote_Count            4830 non-null   float64
 11  Original_Language     4830 non-null   object
 12  Production_Countries  4800 non-null   object
dtypes: float64(6), int64(2), object(5)
memory usage: 507.9+ KB